name: meditation_app
description: A simple Flutter meditation app with meditation streak tracking and video playback.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.21         # For audio playback
  video_player: ^2.4.6        # For video playback
  shared_preferences: ^2.0.15 # For tracking meditation streak

flutter:
  uses-material-design: true

  assets:
    - assets/audio/Nirvana-Shatakam.mp3
    - assets/images/kawai_girl.jpg
    - assets/images/guided_pranayama.png  # Thumbnail image for guided pranayama
    - assets/images/crown_chakra.jpg      # Thumbnail image for crown chakra activation
    - assets/images/Solfeggio_Frequencies.jpg         # Thumbnail image for Solfeggio frequencies meditation
    - assets/images/asmr.jpg
    - assets/images/kawai(2).jpg              # Thumbnail image for ASMR sounds
    - assets/videos/guided_pranayama.mp4
    - assets/videos/crown_chakra.mp4
    - assets/videos/Solfeggio_Frequencies.mp4
    - assets/videos/asmr.mp4
